[manager]
  manager_name = ""
  node_name = ""
  censor_name = ""
  enable_grpc = false
  enable_rest = false
  request_type = ""
  [manager.rest]
    enable = false
    type = ""
    path = ""
    port = ""

[database]
  prefix = ""
  type = ""
  addr = ""
  port = ""
  password = ""
  username = ""
  db = ""

[media]
  upload = ""
  transfer = ""
  m3u8 = ""
  key_url = ""
  key_dest = ""
  key_file = ""
  key_info_file = ""

[queue]
  type = ""
  host_port = ""
  password = ""
  db = 0

[rest]
  enable = false
  type = ""
  path = ""
  port = ""

[ipfs]
  host = ""
  port = ""
