// Code generated by protoc-gen-go. DO NOT EDIT.
// source: censor.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CensorValidateType ...
type CensorValidateType int32

// CensorValidateType_JPG ...
const (
	CensorValidateType_JPG   CensorValidateType = 0
	CensorValidateType_Frame CensorValidateType = 1
	CensorValidateType_Video CensorValidateType = 2
)

// CensorValidateType_name ...
var CensorValidateType_name = map[int32]string{
	0: "JPG",
	1: "Frame",
	2: "Video",
}

// CensorValidateType_value ...
var CensorValidateType_value = map[string]int32{
	"JPG":   0,
	"Frame": 1,
	"Video": 2,
}

// String ...
func (x CensorValidateType) String() string {
	return proto.EnumName(CensorValidateType_name, int32(x))
}

// EnumDescriptor ...
func (CensorValidateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae79c493e7f541d9, []int{0}
}

// ValidateRequest ...
type ValidateRequest struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ObjectKey            string             `protobuf:"bytes,2,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	ValidateType         CensorValidateType `protobuf:"varint,3,opt,name=validateType,proto3,enum=proto.CensorValidateType" json:"validateType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

// Reset ...
func (m *ValidateRequest) Reset() { *m = ValidateRequest{} }

// String ...
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*ValidateRequest) ProtoMessage() {}

// Descriptor ...
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae79c493e7f541d9, []int{0}
}

// XXX_Unmarshal ...
func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}

// XXX_Size ...
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}

// XXX_DiscardUnknown ...
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

// GetID ...
func (m *ValidateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetObjectKey ...
func (m *ValidateRequest) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

// GetValidateType ...
func (m *ValidateRequest) GetValidateType() CensorValidateType {
	if m != nil {
		return m.ValidateType
	}
	return CensorValidateType_JPG
}

// CensorReply ...
type CensorReply struct {
	Code                 int32              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               *CensorReplyDetail `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

// Reset ...
func (m *CensorReply) Reset() { *m = CensorReply{} }

// String ...
func (m *CensorReply) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*CensorReply) ProtoMessage() {}

// Descriptor ...
func (*CensorReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae79c493e7f541d9, []int{1}
}

// XXX_Unmarshal ...
func (m *CensorReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CensorReply.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *CensorReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CensorReply.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *CensorReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CensorReply.Merge(m, src)
}

// XXX_Size ...
func (m *CensorReply) XXX_Size() int {
	return xxx_messageInfo_CensorReply.Size(m)
}

// XXX_DiscardUnknown ...
func (m *CensorReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CensorReply.DiscardUnknown(m)
}

var xxx_messageInfo_CensorReply proto.InternalMessageInfo

// GetCode ...
func (m *CensorReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// GetMessage ...
func (m *CensorReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// GetDetail ...
func (m *CensorReply) GetDetail() *CensorReplyDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

// CensorReplyDetail ...
type CensorReplyDetail struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Json                 string   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

// Reset ...
func (m *CensorReplyDetail) Reset() { *m = CensorReplyDetail{} }

// String ...
func (m *CensorReplyDetail) String() string { return proto.CompactTextString(m) }

// ProtoMessage ...
func (*CensorReplyDetail) ProtoMessage() {}

// Descriptor ...
func (*CensorReplyDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae79c493e7f541d9, []int{2}
}

// XXX_Unmarshal ...
func (m *CensorReplyDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CensorReplyDetail.Unmarshal(m, b)
}

// XXX_Marshal ...
func (m *CensorReplyDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CensorReplyDetail.Marshal(b, m, deterministic)
}

// XXX_Merge ...
func (m *CensorReplyDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CensorReplyDetail.Merge(m, src)
}

// XXX_Size ...
func (m *CensorReplyDetail) XXX_Size() int {
	return xxx_messageInfo_CensorReplyDetail.Size(m)
}

// XXX_DiscardUnknown ...
func (m *CensorReplyDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CensorReplyDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CensorReplyDetail proto.InternalMessageInfo

// GetID ...
func (m *CensorReplyDetail) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// GetJson ...
func (m *CensorReplyDetail) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CensorValidateType", CensorValidateType_name, CensorValidateType_value)
	proto.RegisterType((*ValidateRequest)(nil), "proto.ValidateRequest")
	proto.RegisterType((*CensorReply)(nil), "proto.CensorReply")
	proto.RegisterType((*CensorReplyDetail)(nil), "proto.CensorReplyDetail")
}

func init() { proto.RegisterFile("censor.proto", fileDescriptor_ae79c493e7f541d9) }

var fileDescriptor_ae79c493e7f541d9 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x69, 0xf9, 0x27, 0x03, 0x22, 0xce, 0xc1, 0xac, 0xc6, 0x03, 0xe9, 0x89, 0x78, 0x68,
	0x08, 0x1c, 0xf4, 0xe2, 0x05, 0x89, 0x06, 0xbd, 0x90, 0xd5, 0xf4, 0xde, 0x6e, 0x27, 0xb5, 0xa4,
	0xed, 0xd6, 0x76, 0x21, 0xe9, 0xc5, 0xcf, 0x6e, 0xd8, 0x96, 0x68, 0xed, 0x69, 0x67, 0xe7, 0xbd,
	0x99, 0xdf, 0xbe, 0x85, 0x91, 0xa0, 0x24, 0x97, 0x99, 0x9d, 0x66, 0x52, 0x49, 0xec, 0xea, 0xc3,
	0xfa, 0x86, 0x0b, 0xc7, 0x8d, 0x42, 0xdf, 0x55, 0xc4, 0xe9, 0x6b, 0x4f, 0xb9, 0xc2, 0x31, 0x98,
	0x9b, 0x35, 0x33, 0xa6, 0xc6, 0x6c, 0xc0, 0xcd, 0xcd, 0x1a, 0x6f, 0x61, 0x20, 0xbd, 0x1d, 0x09,
	0xf5, 0x46, 0x05, 0x33, 0x75, 0xfb, 0xb7, 0x81, 0x8f, 0x30, 0x3a, 0x54, 0x0b, 0x3e, 0x8a, 0x94,
	0x58, 0x7b, 0x6a, 0xcc, 0xc6, 0x8b, 0xeb, 0x92, 0x62, 0x3f, 0x69, 0xa4, 0xf3, 0xc7, 0xc0, 0x6b,
	0x76, 0x2b, 0x86, 0x61, 0xe9, 0xe1, 0x94, 0x46, 0x05, 0x22, 0x74, 0x84, 0xf4, 0x49, 0xd3, 0xbb,
	0x5c, 0xd7, 0xc8, 0xa0, 0x1f, 0x53, 0x9e, 0xbb, 0x01, 0x55, 0xf4, 0xd3, 0x15, 0xe7, 0xd0, 0xf3,
	0x49, 0xb9, 0x61, 0xa4, 0xa9, 0xc3, 0x05, 0xab, 0x51, 0xf5, 0xc6, 0xb5, 0xd6, 0x79, 0xe5, 0xb3,
	0xee, 0xe1, 0xb2, 0x21, 0x36, 0x02, 0x23, 0x74, 0x76, 0xb9, 0x4c, 0x2a, 0x9a, 0xae, 0xef, 0x96,
	0x80, 0xcd, 0x2c, 0xd8, 0x87, 0xf6, 0xeb, 0xf6, 0x65, 0xd2, 0xc2, 0x01, 0x74, 0x9f, 0x33, 0x37,
	0xa6, 0x89, 0x71, 0x2c, 0x9d, 0xd0, 0x27, 0x39, 0x31, 0x17, 0x1b, 0x38, 0x2f, 0x87, 0xde, 0x29,
	0x3b, 0x84, 0x82, 0xf0, 0x01, 0xce, 0x4e, 0xf3, 0x78, 0x55, 0x3d, 0xf6, 0xdf, 0xf7, 0xdf, 0x60,
	0x33, 0x84, 0xd5, 0x5a, 0xcd, 0x81, 0x09, 0x19, 0xdb, 0x41, 0xa8, 0x3e, 0xf7, 0x9e, 0x1d, 0x48,
	0x5f, 0xc8, 0x24, 0x28, 0x9d, 0x2b, 0xac, 0x41, 0xb6, 0xc7, 0xde, 0xd6, 0xf0, 0x7a, 0x5a, 0x5c,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x11, 0x92, 0xe6, 0xdb, 0xf7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CensorServiceClient is the client API for CensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CensorServiceClient interface {
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*CensorReply, error)
}

type censorServiceClient struct {
	cc *grpc.ClientConn
}

// NewCensorServiceClient ...
func NewCensorServiceClient(cc *grpc.ClientConn) CensorServiceClient {
	return &censorServiceClient{cc}
}

// Validate ...
func (c *censorServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*CensorReply, error) {
	out := new(CensorReply)
	err := c.cc.Invoke(ctx, "/proto.CensorService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CensorServiceServer is the server API for CensorService service.
type CensorServiceServer interface {
	Validate(context.Context, *ValidateRequest) (*CensorReply, error)
}

// RegisterCensorServiceServer ...
func RegisterCensorServiceServer(s *grpc.Server, srv CensorServiceServer) {
	s.RegisterService(&_CensorService_serviceDesc, srv)
}

func _CensorService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CensorService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CensorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CensorService",
	HandlerType: (*CensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _CensorService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "censor.proto",
}
